//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaserGRBL {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaserGRBL.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Right click here to add custom buttons benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AddCustomButtonsHint {
            get {
                return ResourceManager.GetString("AddCustomButtonsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Abort current job? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BoxAbortProgramConfirm {
            get {
                return ResourceManager.GetString("BoxAbortProgramConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automatic update failed!
        ///Please manually download the new version from lasergrbl site. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BoxAutoUpdateFailed {
            get {
                return ResourceManager.GetString("BoxAutoUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update require administrator privilege! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BoxAutoUpdateRequireAdmin {
            get {
                return ResourceManager.GetString("BoxAutoUpdateRequireAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update result benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BoxAutoUpdateResult {
            get {
                return ResourceManager.GetString("BoxAutoUpdateResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update success! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BoxAutoUpdateSuccess {
            get {
                return ResourceManager.GetString("BoxAutoUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are some changes that have not been applied.
        ///Do you want to rewrite the configuration? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BoxConfigDetectedChanges {
            get {
                return ResourceManager.GetString("BoxConfigDetectedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Changes detected! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BoxConfigDetectedChangesTitle {
            get {
                return ResourceManager.GetString("BoxConfigDetectedChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot connect to device benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BoxConnectErrorTitle {
            get {
                return ResourceManager.GetString("BoxConnectErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please provide GCode commands benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BoxCustomButtonPleaseGCodeText {
            get {
                return ResourceManager.GetString("BoxCustomButtonPleaseGCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please provide tooltip text benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BoxCustomButtonPleaseToolTipText {
            get {
                return ResourceManager.GetString("BoxCustomButtonPleaseToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Missing field benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BoxCustomButtonPleaseToolTipTitle {
            get {
                return ResourceManager.GetString("BoxCustomButtonPleaseToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure to delete selected button? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BoxDeleteCustomButtonText {
            get {
                return ResourceManager.GetString("BoxDeleteCustomButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete custom button benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BoxDeleteCustomButtonTitle {
            get {
                return ResourceManager.GetString("BoxDeleteCustomButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error exporting config! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BoxExportConfigError {
            get {
                return ResourceManager.GetString("BoxExportConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BoxExportConfigErrorTitle {
            get {
                return ResourceManager.GetString("BoxExportConfigErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File does not exist! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BoxExportConfigFileNotFound {
            get {
                return ResourceManager.GetString("BoxExportConfigFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} Config exported successfully! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BoxExportConfigSuccess {
            get {
                return ResourceManager.GetString("BoxExportConfigSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Success benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BoxExportConfigSuccessTitle {
            get {
                return ResourceManager.GetString("BoxExportConfigSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error reading file! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BoxImportConfigFileError {
            get {
                return ResourceManager.GetString("BoxImportConfigFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} Config imported with {1} errors! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BoxImportConfigWithError {
            get {
                return ResourceManager.GetString("BoxImportConfigWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} Config imported successfully! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BoxImportConfigWithoutError {
            get {
                return ResourceManager.GetString("BoxImportConfigWithoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import custom button benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BoxImportCustomButtonCaption {
            get {
                return ResourceManager.GetString("BoxImportCustomButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove actual buttons? Select yes to remove, no to keep. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BoxImportCustomButtonClearText {
            get {
                return ResourceManager.GetString("BoxImportCustomButtonClearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirmation benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BoxImportCustomButtonrCaption {
            get {
                return ResourceManager.GetString("BoxImportCustomButtonrCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error reading config! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BoxReadConfigError {
            get {
                return ResourceManager.GetString("BoxReadConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Showing cached values... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BoxReadConfigPleaseConnect {
            get {
                return ResourceManager.GetString("BoxReadConfigPleaseConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} Config readed successfully! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BoxReadConfigSuccess {
            get {
                return ResourceManager.GetString("BoxReadConfigSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No changes... nothing to write! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BoxWriteConfigNoChange {
            get {
                return ResourceManager.GetString("BoxWriteConfigNoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} Config written with {1} errors! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BoxWriteConfigWithError {
            get {
                return ResourceManager.GetString("BoxWriteConfigWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} Config written successfully! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BoxWriteConfigWithoutError {
            get {
                return ResourceManager.GetString("BoxWriteConfigWithoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connect benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BtnConnectTT {
            get {
                return ResourceManager.GetString("BtnConnectTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disconnect benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BtnDisconnectTT {
            get {
                return ResourceManager.GetString("BtnDisconnectTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit button benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CustomButtonEdit {
            get {
                return ResourceManager.GetString("CustomButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove button benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CustomButtonRemove {
            get {
                return ResourceManager.GetString("CustomButtonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diagonal (old) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DirectionDiagonal {
            get {
                return ResourceManager.GetString("DirectionDiagonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Horizontal (old) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DirectionHorizontal {
            get {
                return ResourceManager.GetString("DirectionHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cross Fill benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DirectionNewCross {
            get {
                return ResourceManager.GetString("DirectionNewCross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diagonal benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DirectionNewDiagonal {
            get {
                return ResourceManager.GetString("DirectionNewDiagonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diagonal Cross Fill benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DirectionNewDiagonalCross {
            get {
                return ResourceManager.GetString("DirectionNewDiagonalCross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diagonal Grid benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DirectionNewDiagonalGrid {
            get {
                return ResourceManager.GetString("DirectionNewDiagonalGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grid benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DirectionNewGrid {
            get {
                return ResourceManager.GetString("DirectionNewGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hilbert benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DirectionNewHilbert {
            get {
                return ResourceManager.GetString("DirectionNewHilbert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Horizontal benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DirectionNewHorizontal {
            get {
                return ResourceManager.GetString("DirectionNewHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inset Filling benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DirectionNewInsetFilling {
            get {
                return ResourceManager.GetString("DirectionNewInsetFilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diagonal Reversed benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DirectionNewReverseDiagonal {
            get {
                return ResourceManager.GetString("DirectionNewReverseDiagonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Squares benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DirectionNewSquares {
            get {
                return ResourceManager.GetString("DirectionNewSquares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vertical benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DirectionNewVertical {
            get {
                return ResourceManager.GetString("DirectionNewVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zig Zag benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DirectionNewZigZag {
            get {
                return ResourceManager.GetString("DirectionNewZigZag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Filling benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DirectionNone {
            get {
                return ResourceManager.GetString("DirectionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vertical (old) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DirectionVertical {
            get {
                return ResourceManager.GetString("DirectionVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File transfer in progress. Disconnect anyway? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DisconnectAnyway {
            get {
                return ResourceManager.GetString("DisconnectAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dithering Options benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DitheringOptions {
            get {
                return ResourceManager.GetString("DitheringOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File transfer in progress. Exit anyway? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ExitAnyway {
            get {
                return ResourceManager.GetString("ExitAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restart required benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FirmwareRequireRestart {
            get {
                return ResourceManager.GetString("FirmwareRequireRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restart is required to apply Firmware type changes. Restart now? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FirmwareRequireRestartNow {
            get {
                return ResourceManager.GetString("FirmwareRequireRestartNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FormulaCustom {
            get {
                return ResourceManager.GetString("FormulaCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OpticalCorrect benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FormulaOpticalCorrect {
            get {
                return ResourceManager.GetString("FormulaOpticalCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SimpleAverage benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FormulaSimpleAverage {
            get {
                return ResourceManager.GetString("FormulaSimpleAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WeightAverage benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FormulaWeightAverage {
            get {
                return ResourceManager.GetString("FormulaWeightAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Smooth (HQ Bicubic) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string InterpolationModeHighQualityBicubic {
            get {
                return ResourceManager.GetString("InterpolationModeHighQualityBicubic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sharp (NearestNeighbor) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string InterpolationModeNearestNeighbor {
            get {
                return ResourceManager.GetString("InterpolationModeNearestNeighbor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restart required benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LanguageRequireRestart {
            get {
                return ResourceManager.GetString("LanguageRequireRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Require application restart, restart now? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LanguageRequireRestartNow {
            get {
                return ResourceManager.GetString("LanguageRequireRestartNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line To Line Options benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Line2LineOptions {
            get {
                return ResourceManager.GetString("Line2LineOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alarm benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MacStatusAlarm {
            get {
                return ResourceManager.GetString("MacStatusAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MacStatusCheck {
            get {
                return ResourceManager.GetString("MacStatusCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connecting benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MacStatusConnecting {
            get {
                return ResourceManager.GetString("MacStatusConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disconnected benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MacStatusDisconnected {
            get {
                return ResourceManager.GetString("MacStatusDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Door benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MacStatusDoor {
            get {
                return ResourceManager.GetString("MacStatusDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hold benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MacStatusHold {
            get {
                return ResourceManager.GetString("MacStatusHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Home benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MacStatusHome {
            get {
                return ResourceManager.GetString("MacStatusHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Idle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MacStatusIdle {
            get {
                return ResourceManager.GetString("MacStatusIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jog benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MacStatusJog {
            get {
                return ResourceManager.GetString("MacStatusJog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MacStatusRun {
            get {
                return ResourceManager.GetString("MacStatusRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MacStatusUnknown {
            get {
                return ResourceManager.GetString("MacStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Estimated Time: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MainFormEstimatedTime {
            get {
                return ResourceManager.GetString("MainFormEstimatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Projected Time: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MainFormProjectedTime {
            get {
                return ResourceManager.GetString("MainFormProjectedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot open a new file now. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MsgboxCannotOpenFileNow {
            get {
                return ResourceManager.GetString("MsgboxCannotOpenFileNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It seems that the current position is no longer known by Grbl.
        ///Without the Homing Procedure ($H) the result may not be reliable.
        ///Continue anyway? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ResumeJobHomingRequired {
            get {
                return ResourceManager.GetString("ResumeJobHomingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown position benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ResumeJobHomingRequiredTitle {
            get {
                return ResourceManager.GetString("ResumeJobHomingRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Speed: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SpeedSliderToolTip {
            get {
                return ResourceManager.GetString("SpeedSliderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Step: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StepSliderToolTip {
            get {
                return ResourceManager.GetString("StepSliderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This file type is not supported. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string UnsupportedFiletype {
            get {
                return ResourceManager.GetString("UnsupportedFiletype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Centerline option is not compatible with your PC.
        ///64bit OS is needed! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string WarnCenterline64bit {
            get {
                return ResourceManager.GetString("WarnCenterline64bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line2Line option is not compatible with your engraver or with your configuration. PWM-able laser is needed, and PWM support should be enabled in LaserGRBL settings. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string WarnLine2LinePWM {
            get {
                return ResourceManager.GetString("WarnLine2LinePWM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string WarnMessageBoxHeader {
            get {
                return ResourceManager.GetString("WarnMessageBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You have set negative offsets, but your engraver is set to use positive space with soft limit alarm enabled ($20=1).
        ///
        ///This could generate a soft-limit error. Are you sure of the entered values? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string WarnSoftLimitNS {
            get {
                return ResourceManager.GetString("WarnSoftLimitNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You have set a size and offset that makes the job larger than the workspace configured in your engraver ({0}mm x {1}mm).
        ///Grbl Parameters $130 and $131.
        ///
        ///This could generate a soft-limit error or the machine could crash into the axes boundary. Are you sure of the entered values? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string WarnSoftLimitOOB {
            get {
                return ResourceManager.GetString("WarnSoftLimitOOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Job boundary confirmation benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string WarnSoftLimitTitle {
            get {
                return ResourceManager.GetString("WarnSoftLimitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;M4 Dynamic Laser Power Mode&quot; has been set, but your engraver doesn&apos;t seem to support it.
        ///Only engravers with grbl version &gt;= 1.1 with &quot;laser mode&quot; enabled ($32=1) can take advantage of M4 option. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string WarnWrongLaserMode {
            get {
                return ResourceManager.GetString("WarnWrongLaserMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string WarnWrongLaserModeTitle {
            get {
                return ResourceManager.GetString("WarnWrongLaserModeTitle", resourceCulture);
            }
        }
    }
}
